title: Akihisa Konno
description: Research, education, and open-source projects
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
plugins:
  - jekyll-include-cache

lang: en
url: https://akonno.github.io
